server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: kblog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456

debug: false

